import GameplayStage from "./gameplayStage";
import { GAMEPLAY_ORDINARYWORLD_HOUSE_DIALOGUES, GAMEPLAY_ORDINARYWORLD_TOWN_DIALOGUES, GAMEPLAY_ORDINARYWORLD_PRETRAINING_DIALOGUES } from "./gameplayStages/ordinaryWorldDialogues";

export const GAMEPLAY_STAGES: GameplayStage[] = [
    GAMEPLAY_ORDINARYWORLD_HOUSE_DIALOGUES,
    GAMEPLAY_ORDINARYWORLD_TOWN_DIALOGUES,
    GAMEPLAY_ORDINARYWORLD_PRETRAINING_DIALOGUES
]